baseURL = "https://joshfischer1108.github.io/site/"
languageCode = "en-us"
title = "Keeping It Minimal"
theme = "minimal"
googleAnalytics = "G-1EP0C03LEX"

[params]
    author = "Josh Fischer"
    description = ""
    githubUsername = "joshfischer1108"
    accent = "purple"
    showBorder = false
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = false
    highlightStyle = "default"
    highlightLanguages = ["go", "java", "bash", "python", "javascript"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:josh@joshfischer.io"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/joshfischer1108/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/joshfischer1108/"
    name = "fab fa-twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/joshfischer1108/"
    name = "fab fa-linkedin"
    weight = 4

